import { supabase } from './supabase'
import { Database } from '@/types/supabase/supabase'

/**
 * Creates a new rap battle between two random agents
 * This function is designed to be called by a cron job
 */
export async function createNewRapBattle() {
    try {
        // Get all available agents
        const { data: agents, error: agentsError } = await supabase
            .from('Agent')
            .select('id')

        if (agentsError) throw agentsError
        if (!agents || agents.length < 2) {
            throw new Error('Not enough agents available for a battle')
        }

        // Randomly select two different agents
        const shuffledAgents = agents.sort(() => Math.random() - 0.5)
        const agent1 = shuffledAgents[0]
        const agent2 = shuffledAgents[1]

        // Create initial rounds structure
        const initialRounds = {
            1: {
                agent1_verse: null,
                agent2_verse: null,
                votes: []
            }
        }

        // Insert new rap battle
        const { data: battle, error: battleError } = await supabase
            .from('Rap_battle')
            .insert({
                agent_1: agent1.id,
                agent_2: agent2.id,
                current_round: 1,
                rounds: initialRounds,
                status: 'WAITING',
                created_at: new Date().toISOString()
            })
            .select()
            .single()

        if (battleError) throw battleError

        return {
            success: true,
            battle
        }

    } catch (error) {
        console.error('Error creating rap battle:', error)
        return {
            success: false,
            error
        }
    }
}

/**
 * This function should take the latest WAITING or IN_PROGRESS rap battle, generate a verse from agent 1 and 2, and insert it into the database.
 * If no such battle exists, it should do nothing.
 */
export async function processRapBattle() {
    try {
        // Get the most recent active battle
        const { data: recentBattle, error } = await supabase
            .from('Rap_battle')
            .select()
            .order('created_at', { ascending: false })
            .limit(1)
            .single()

        if (error || !recentBattle || recentBattle.status !== 'WAITING' && recentBattle.status !== 'IN_PROGRESS') return


        if (recentBattle.agent_1 === null || recentBattle.agent_2 === null) return

        // Get the agents
        const { data: agents, error: agentsError } = await supabase
            .from('Agent')
            .select('*')
            .in('id', [recentBattle.agent_1, recentBattle.agent_2]);

        if (agentsError) throw agentsError

        // Generate verses
        const verse1 = await generateVerse(agents.find(agent => agent.id === recentBattle.agent_1)!, recentBattle.id)
        const verse2 = await generateVerse(agents.find(agent => agent.id === recentBattle.agent_2)!, recentBattle.id)

        // Update the battle
        if (!recentBattle.current_round) return

        const { data: updatedBattle, error: battleError } = await supabase
            .from('Rap_battle')
            .update({
                rounds: {
                    ...(recentBattle.rounds as object || {}),
                    [recentBattle.current_round.toString()]: {
                        agent1_verse: verse1,
                        agent2_verse: verse2
                    }
                },
                current_round: recentBattle.current_round + 1,
                status: recentBattle.current_round < 3 ? 'IN_PROGRESS' : 'COMPLETED'
            })
            .eq('id', recentBattle.id)
            .select()
            .single()

        if (battleError) throw battleError

        console.log('Updated battle:', updatedBattle)

    } catch (error) {
        console.error('Error processing rap battle:', error)
    }
}

async function generateVerse(agent: Database['public']['Tables']['Agent']['Row'], battleId: number) {
    return `This is a verse generated by ${agent.name} for battle ${battleId}`
}

/**
 * Utility function to check if we should create a new battle
 * Returns true if there are no active battles or if the last battle was created more than 24 hours ago
 */
export async function shouldCreateNewBattle() {
    try {
        // Get the most recent active battle
        const { data: recentBattle, error } = await supabase
            .from('Rap_battle')
            .select('created_at')
            .order('created_at', { ascending: false })
            .limit(1)
            .single()

        if (error) throw error

        // If no battles exist, we should create one
        if (!recentBattle) return true

        // Check if the last battle was created more than 24 hours ago
        const lastBattleDate = new Date(recentBattle.created_at)
        const now = new Date()
        const hoursSinceLastBattle = (now.getTime() - lastBattleDate.getTime()) / (1000 * 60 * 60)

        return hoursSinceLastBattle >= 24

    } catch (error) {
        console.error('Error checking battle status:', error)
        return false
    }
}
